
/* controls.h	   Created:    1990-10-22  Revised:    1993-03-02	*/

/* Controls Styles Header						*/

/* Copyright ¸ International Business Machines Corp., 1991,1992,1993.	*/
/* Copyright ¸ 1989-1993  Prominare Inc.  All Rights Reserved.		*/



/* --- Text Styles ----------------------------------------------------	*/

#define	DS_DEPRESSED	  0x0000L
#define	DS_RAISED	  0x0040L

/* --- Line Styles ----------------------------------------------------	*/

#define	LNS_VERTICAL	  0x0001L
#define	LNS_HORIZONTAL	  0x0002L
